### ISSUE TITLE
Dolby shut down after maps

### ISSUE THREAD

**Issue by alessio89g** [reiryuki/Dolby-Audio-Moto-G-Pro-Magisk-Module#1]
Hi,
is there any way to restart Dolby's service?
I ask for that because I found an issue:
when the voice assistant of Google Maps starts to talk to guide me, and then I close Maps, Dolby stops working; no FCs, errors, messages or notifications, but all the Android UI sounds play lower, as if Dolby wasn't installed. I tried to turn off and on again the app toggle, to select another preset and change the volume level, but the only way to get Dolby working again is to reboot the device.
I found this issue on all the Android 12/13 ROMs I tried, both with your Magisk zip or integrated into the ROM.
My device is a OnePlus 7 Pro (GM1910), currently running unofficial RiceDroid 13 (there integrated into the ROM).
If can help the voice assistant of Maps is in Italian.
Best regards.

**Comment by reiryuki** [comment]
read Troubleshootings!
